# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 
      - dev
      - master
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches: 
      - dev
      - master
      - 'release/**'

jobs:
  linux-aarch64:
    name: Linux (aarch64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Dtarget.platform=linux-aarch64
    - run: mkdir staging && cp -r target/shade/ staging
    - uses: actions/upload-artifact@v3
      with:
        name: Lilith's Throne (linux-aarch64)
        path: staging
  
  linux:
    name: Linux (amd64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Dtarget.platform=linux
    - run: mkdir staging && cp -r target/shade/ staging
    - uses: actions/upload-artifact@v3
      with:
        name: Lilith's Throne (linux)
        path: staging

  mac-aarch64:
    name: Mac (aarch64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Dtarget.platform=mac-aarch64
    - run: mkdir staging && cp -r target/shade/ staging
    - uses: actions/upload-artifact@v3
      with:
        name: Lilith's Throne (mac-aarch64)
        path: staging

  mac:
    name: Mac (amd64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Dtarget.platform=mac
    - run: mkdir staging && cp -r target/shade/ staging
    - uses: actions/upload-artifact@v3
      with:
        name: Lilith's Throne (mac)
        path: staging

  win-x86:
    name: Windows (x86)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Dtarget.platform=win-x86
    - run: mkdir staging && cp -r target/shade/ staging
    - uses: actions/upload-artifact@v3
      with:
        name: Lilith's Throne (win-x86)
        path: staging
  
  win:
    name: Windows (amd64)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -Dtarget.platform=win
    - run: mkdir staging && cp -r target/shade/ staging
    - uses: actions/upload-artifact@v3
      with:
        name: Lilith's Throne (win)
        path: staging